import sqlite3 as sq
import random
import leaderboards
from PyQt5 import QtCore, QtGui, QtWidgets
from person import person
Player = None
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.main_window = MainWindow
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(784, 513)
        MainWindow.setFixedSize(784,513)
        font = QtGui.QFont()
        font.setPointSize(9)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 10, 1100, 600))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.hint_button = QtWidgets.QPushButton(self.groupBox_2)
        self.hint_button.setGeometry(QtCore.QRect(420, 40, 91, 31))
        self.hint_button.setObjectName("hint_button")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox.setEnabled(True)
        self.groupBox.setGeometry(QtCore.QRect(30, 20, 221, 121))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 20, 221, 90))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.username_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(9)
        self.username_label.setFont(font)
        self.username_label.setText("")
        self.username_label.setObjectName("username_label")
        self.verticalLayout_3.addWidget(self.username_label)
        self.score_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(9)
        self.score_label.setFont(font)
        self.score_label.setText("")
        self.score_label.setObjectName("score_label")
        self.verticalLayout_3.addWidget(self.score_label)
        self.highscore_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(9)
        self.highscore_label.setFont(font)
        self.highscore_label.setText("")
        self.highscore_label.setObjectName("highscore_label")
        self.verticalLayout_3.addWidget(self.highscore_label)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.line_16 = QtWidgets.QFrame(self.groupBox_2)
        self.line_16.setGeometry(QtCore.QRect(342, 290, 21, 16))
        self.line_16.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_16.setLineWidth(2)
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setObjectName("line_16")
        self.line_9 = QtWidgets.QFrame(self.groupBox_2)
        self.line_9.setGeometry(QtCore.QRect(350, 310, 16, 91))
        self.line_9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_9.setLineWidth(2)
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setObjectName("line_9")
        self.line_14 = QtWidgets.QFrame(self.groupBox_2)
        self.line_14.setGeometry(QtCore.QRect(330, 270, 16, 16))
        self.line_14.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_14.setLineWidth(2)
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setObjectName("line_14")
        self.line1 = QtWidgets.QFrame(self.groupBox_2)
        self.line1.setGeometry(QtCore.QRect(30, 540, 150, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line1.sizePolicy().hasHeightForWidth())
        self.line1.setSizePolicy(sizePolicy)
        self.line1.setMinimumSize(QtCore.QSize(150, 30))
        self.line1.setMaximumSize(QtCore.QSize(150, 30))
        self.line1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line1.setLineWidth(5)
        self.line1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line1.setObjectName("line1")
        self.line2 = QtWidgets.QFrame(self.groupBox_2)
        self.line2.setGeometry(QtCore.QRect(90, 205, 30, 350))
        self.line2.setMinimumSize(QtCore.QSize(30, 350))
        self.line2.setMaximumSize(QtCore.QSize(30, 350))
        self.line2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line2.setLineWidth(5)
        self.line2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line2.setObjectName("line2")
        self.line_15 = QtWidgets.QFrame(self.groupBox_2)
        self.line_15.setGeometry(QtCore.QRect(360, 270, 16, 16))
        self.line_15.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_15.setLineWidth(2)
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setObjectName("line_15")
        self.line_13 = QtWidgets.QFrame(self.groupBox_2)
        self.line_13.setGeometry(QtCore.QRect(358, 340, 42, 16))
        self.line_13.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_13.setLineWidth(2)
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setObjectName("line_13")
        self.line4 = QtWidgets.QFrame(self.groupBox_2)
        self.line4.setGeometry(QtCore.QRect(345, 206, 16, 51))
        self.line4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line4.setLineWidth(5)
        self.line4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line4.setObjectName("line4")
        self.line_11 = QtWidgets.QFrame(self.groupBox_2)
        self.line_11.setGeometry(QtCore.QRect(310, 392, 51, 16))
        self.line_11.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_11.setLineWidth(2)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setObjectName("line_11")
        self.line_7 = QtWidgets.QFrame(self.groupBox_2)
        self.line_7.setGeometry(QtCore.QRect(328, 300, 51, 16))
        self.line_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_7.setLineWidth(2)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setObjectName("line_7")
        self.line_6 = QtWidgets.QFrame(self.groupBox_2)
        self.line_6.setGeometry(QtCore.QRect(370, 258, 16, 51))
        self.line_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_6.setLineWidth(2)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setObjectName("line_6")
        self.line3 = QtWidgets.QFrame(self.groupBox_2)
        self.line3.setGeometry(QtCore.QRect(104, 192, 251, 31))
        self.line3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line3.setLineWidth(5)
        self.line3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line3.setObjectName("line3")
        self.line_8 = QtWidgets.QFrame(self.groupBox_2)
        self.line_8.setGeometry(QtCore.QRect(328, 250, 51, 16))
        self.line_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_8.setLineWidth(2)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setObjectName("line_8")
        self.line_12 = QtWidgets.QFrame(self.groupBox_2)
        self.line_12.setGeometry(QtCore.QRect(315, 340, 42, 16))
        self.line_12.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_12.setLineWidth(2)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setObjectName("line_12")
        self.line_10 = QtWidgets.QFrame(self.groupBox_2)
        self.line_10.setGeometry(QtCore.QRect(360, 392, 51, 16))
        self.line_10.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_10.setLineWidth(2)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setObjectName("line_10")
        self.line_5 = QtWidgets.QFrame(self.groupBox_2)
        self.line_5.setGeometry(QtCore.QRect(320, 258, 16, 51))
        self.line_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_5.setLineWidth(2)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setObjectName("line_5")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(530, 300, 559, 158))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, -1, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.A = QtWidgets.QPushButton(self.layoutWidget1)
        self.A.setMinimumSize(QtCore.QSize(35, 35))
        self.A.setMaximumSize(QtCore.QSize(35, 35))
        self.A.setObjectName("A")
        self.horizontalLayout.addWidget(self.A)
        self.B = QtWidgets.QPushButton(self.layoutWidget1)
        self.B.setMinimumSize(QtCore.QSize(35, 35))
        self.B.setMaximumSize(QtCore.QSize(35, 35))
        self.B.setObjectName("B")
        self.horizontalLayout.addWidget(self.B)
        self.C = QtWidgets.QPushButton(self.layoutWidget1)
        self.C.setMinimumSize(QtCore.QSize(35, 35))
        self.C.setMaximumSize(QtCore.QSize(35, 35))
        self.C.setObjectName("C")
        self.horizontalLayout.addWidget(self.C)
        self.D = QtWidgets.QPushButton(self.layoutWidget1)
        self.D.setMinimumSize(QtCore.QSize(35, 35))
        self.D.setMaximumSize(QtCore.QSize(35, 35))
        self.D.setObjectName("D")
        self.horizontalLayout.addWidget(self.D)
        self.E = QtWidgets.QPushButton(self.layoutWidget1)
        self.E.setMinimumSize(QtCore.QSize(35, 35))
        self.E.setMaximumSize(QtCore.QSize(35, 35))
        self.E.setObjectName("E")
        self.horizontalLayout.addWidget(self.E)
        self.F = QtWidgets.QPushButton(self.layoutWidget1)
        self.F.setMinimumSize(QtCore.QSize(35, 35))
        self.F.setMaximumSize(QtCore.QSize(35, 35))
        self.F.setObjectName("F")
        self.horizontalLayout.addWidget(self.F)
        self.G = QtWidgets.QPushButton(self.layoutWidget1)
        self.G.setMinimumSize(QtCore.QSize(35, 35))
        self.G.setMaximumSize(QtCore.QSize(35, 35))
        self.G.setObjectName("G")
        self.horizontalLayout.addWidget(self.G)
        self.H = QtWidgets.QPushButton(self.layoutWidget1)
        self.H.setMinimumSize(QtCore.QSize(35, 35))
        self.H.setMaximumSize(QtCore.QSize(35, 35))
        self.H.setObjectName("H")
        self.horizontalLayout.addWidget(self.H)
        self.I = QtWidgets.QPushButton(self.layoutWidget1)
        self.I.setEnabled(True)
        self.I.setMinimumSize(QtCore.QSize(35, 35))
        self.I.setMaximumSize(QtCore.QSize(35, 35))
        self.I.setObjectName("I")
        self.horizontalLayout.addWidget(self.I)
        self.J = QtWidgets.QPushButton(self.layoutWidget1)
        self.J.setMinimumSize(QtCore.QSize(35, 35))
        self.J.setMaximumSize(QtCore.QSize(35, 35))
        self.J.setObjectName("J")
        self.horizontalLayout.addWidget(self.J)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, -1, 10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.K = QtWidgets.QPushButton(self.layoutWidget1)
        self.K.setMinimumSize(QtCore.QSize(35, 35))
        self.K.setMaximumSize(QtCore.QSize(35, 35))
        self.K.setObjectName("K")
        self.horizontalLayout_2.addWidget(self.K)
        self.L = QtWidgets.QPushButton(self.layoutWidget1)
        self.L.setMinimumSize(QtCore.QSize(35, 35))
        self.L.setMaximumSize(QtCore.QSize(35, 35))
        self.L.setObjectName("L")
        self.horizontalLayout_2.addWidget(self.L)
        self.M = QtWidgets.QPushButton(self.layoutWidget1)
        self.M.setMinimumSize(QtCore.QSize(35, 35))
        self.M.setMaximumSize(QtCore.QSize(35, 35))
        self.M.setObjectName("M")
        self.horizontalLayout_2.addWidget(self.M)
        self.N = QtWidgets.QPushButton(self.layoutWidget1)
        self.N.setMinimumSize(QtCore.QSize(35, 35))
        self.N.setMaximumSize(QtCore.QSize(35, 35))
        self.N.setObjectName("N")
        self.horizontalLayout_2.addWidget(self.N)
        self.O = QtWidgets.QPushButton(self.layoutWidget1)
        self.O.setMinimumSize(QtCore.QSize(35, 35))
        self.O.setMaximumSize(QtCore.QSize(35, 35))
        self.O.setObjectName("O")
        self.horizontalLayout_2.addWidget(self.O)
        self.P = QtWidgets.QPushButton(self.layoutWidget1)
        self.P.setMinimumSize(QtCore.QSize(35, 35))
        self.P.setMaximumSize(QtCore.QSize(35, 35))
        self.P.setObjectName("P")
        self.horizontalLayout_2.addWidget(self.P)
        self.Q = QtWidgets.QPushButton(self.layoutWidget1)
        self.Q.setMinimumSize(QtCore.QSize(35, 35))
        self.Q.setMaximumSize(QtCore.QSize(35, 35))
        self.Q.setObjectName("Q")
        self.horizontalLayout_2.addWidget(self.Q)
        self.R = QtWidgets.QPushButton(self.layoutWidget1)
        self.R.setMinimumSize(QtCore.QSize(35, 35))
        self.R.setMaximumSize(QtCore.QSize(35, 35))
        self.R.setObjectName("R")
        self.horizontalLayout_2.addWidget(self.R)
        self.S = QtWidgets.QPushButton(self.layoutWidget1)
        self.S.setMinimumSize(QtCore.QSize(35, 35))
        self.S.setMaximumSize(QtCore.QSize(35, 35))
        self.S.setObjectName("S")
        self.horizontalLayout_2.addWidget(self.S)
        self.T = QtWidgets.QPushButton(self.layoutWidget1)
        self.T.setMinimumSize(QtCore.QSize(35, 35))
        self.T.setMaximumSize(QtCore.QSize(35, 35))
        self.T.setObjectName("T")
        self.horizontalLayout_2.addWidget(self.T)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(85, -1, 85, -1)
        self.horizontalLayout_3.setSpacing(7)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.U = QtWidgets.QPushButton(self.layoutWidget1)
        self.U.setMinimumSize(QtCore.QSize(35, 35))
        self.U.setMaximumSize(QtCore.QSize(35, 35))
        self.U.setObjectName("U")
        self.horizontalLayout_3.addWidget(self.U)
        self.V = QtWidgets.QPushButton(self.layoutWidget1)
        self.V.setMinimumSize(QtCore.QSize(35, 35))
        self.V.setMaximumSize(QtCore.QSize(35, 35))
        self.V.setObjectName("V")
        self.horizontalLayout_3.addWidget(self.V)
        self.W = QtWidgets.QPushButton(self.layoutWidget1)
        self.W.setMinimumSize(QtCore.QSize(35, 35))
        self.W.setMaximumSize(QtCore.QSize(35, 35))
        self.W.setObjectName("W")
        self.horizontalLayout_3.addWidget(self.W)
        self.X = QtWidgets.QPushButton(self.layoutWidget1)
        self.X.setMinimumSize(QtCore.QSize(35, 35))
        self.X.setMaximumSize(QtCore.QSize(35, 35))
        self.X.setObjectName("X")
        self.horizontalLayout_3.addWidget(self.X)
        self.Y = QtWidgets.QPushButton(self.layoutWidget1)
        self.Y.setMinimumSize(QtCore.QSize(35, 35))
        self.Y.setMaximumSize(QtCore.QSize(35, 35))
        self.Y.setObjectName("Y")
        self.horizontalLayout_3.addWidget(self.Y)
        self.Z = QtWidgets.QPushButton(self.layoutWidget1)
        self.Z.setMinimumSize(QtCore.QSize(35, 35))
        self.Z.setMaximumSize(QtCore.QSize(35, 35))
        self.Z.setObjectName("Z")
        self.horizontalLayout_3.addWidget(self.Z)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.savenexit_button = QtWidgets.QPushButton(self.groupBox_2)
        self.savenexit_button.setGeometry(QtCore.QRect(680, 530, 121, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.savenexit_button.setFont(font)
        self.savenexit_button.setObjectName("savenexit_button")
        self.word_label = QtWidgets.QLabel(self.groupBox_2)
        self.word_label.setGeometry(QtCore.QRect(540, 170, 401, 71))
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.word_label.setFont(font)
        self.word_label.setLineWidth(1)
        self.word_label.setMidLineWidth(1)
        self.word_label.setText("")
        self.word_label.setAlignment(QtCore.Qt.AlignCenter)
        self.word_label.setWordWrap(False)
        self.word_label.setIndent(-1)
        self.word_label.setObjectName("word_label")
        self.initial_page = QtWidgets.QGroupBox(self.centralwidget)
        self.initial_page.setGeometry(QtCore.QRect(-90, -30, 811, 581))
        self.initial_page.setTitle("")
        self.initial_page.setObjectName("initial_page")
        self.tabWidget = QtWidgets.QTabWidget(self.initial_page)
        self.tabWidget.setGeometry(QtCore.QRect(180, 60, 601, 401))
        self.tabWidget.setObjectName("tabWidget")
        self.signin = QtWidgets.QWidget()
        self.signin.setObjectName("signin")
        self.warninglabel = QtWidgets.QLabel(self.signin)
        self.warninglabel.setGeometry(QtCore.QRect(180, 150, 211, 31))
        self.warninglabel.setText("")
        self.warninglabel.setObjectName("warninglabel")
        self.widget = QtWidgets.QWidget(self.signin)
        self.widget.setGeometry(QtCore.QRect(200, 90, 151, 51))
        self.widget.setObjectName("widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_4.addWidget(self.lineEdit)
        self.widget1 = QtWidgets.QWidget(self.signin)
        self.widget1.setGeometry(QtCore.QRect(180, 190, 195, 30))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_5.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.widget1)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_5.addWidget(self.pushButton)
        self.tabWidget.addTab(self.signin, "")
        self.signup = QtWidgets.QWidget()
        self.signup.setObjectName("signup")
        self.layoutWidget_2 = QtWidgets.QWidget(self.signup)
        self.layoutWidget_2.setGeometry(QtCore.QRect(180, 190, 195, 30))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_6.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_6.addWidget(self.pushButton_4)
        self.warninglabel_2 = QtWidgets.QLabel(self.signup)
        self.warninglabel_2.setGeometry(QtCore.QRect(180, 150, 211, 31))
        self.warninglabel_2.setText("")
        self.warninglabel_2.setObjectName("warninglabel_2")
        self.widget2 = QtWidgets.QWidget(self.signup)
        self.widget2.setGeometry(QtCore.QRect(200, 90, 151, 51))
        self.widget2.setObjectName("widget2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.widget2)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_5.addWidget(self.lineEdit_2)
        self.tabWidget.addTab(self.signup, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 784, 26))
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setGeometry(QtCore.QRect(288, 187, 159, 150))
        self.menufile.setObjectName("menufile")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew_Game = QtWidgets.QAction(MainWindow)
        self.actionNew_Game.setObjectName("actionNew_Game")
        self.actionSwith_User = QtWidgets.QAction(MainWindow)
        self.actionSwith_User.setObjectName("actionSwith_User")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionLeaderboards = QtWidgets.QAction(MainWindow)
        self.actionLeaderboards.setObjectName("actionLeaderboards")
        self.actionUser_Info = QtWidgets.QAction(MainWindow)
        self.actionUser_Info.setObjectName("actionUser_Info")
        self.actionSource_Info = QtWidgets.QAction(MainWindow)
        self.actionSource_Info.setObjectName("actionSource_Info")
        self.actionHangman_Help = QtWidgets.QAction(MainWindow)
        self.actionHangman_Help.setObjectName("actionHangman_Help")
        self.actionAbout_Us = QtWidgets.QAction(MainWindow)
        self.actionAbout_Us.setObjectName("actionAbout_Us")
        self.menufile.addAction(self.actionNew_Game)
        self.menufile.addAction(self.actionSwith_User)
        self.menufile.addAction(self.actionSettings)
        self.menufile.addAction(self.actionExit)
        self.menuView.addAction(self.actionLeaderboards)
        self.menuView.addAction(self.actionUser_Info)
        self.menuView.addAction(self.actionSource_Info)
        self.menuAbout.addAction(self.actionHangman_Help)
        self.menuAbout.addAction(self.actionAbout_Us)
        self.menubar.addAction(self.menufile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())
        self.groupBox_2.hide()
        self.A.clicked.connect(self.on_A_clicked)
        self.B.clicked.connect(self.on_B_clicked)       
        self.C.clicked.connect(self.on_C_clicked)
        self.D.clicked.connect(self.on_D_clicked)
        self.E.clicked.connect(self.on_E_clicked)
        self.F.clicked.connect(self.on_F_clicked)
        self.G.clicked.connect(self.on_G_clicked)
        self.H.clicked.connect(self.on_H_clicked)
        self.I.clicked.connect(self.on_I_clicked)
        self.J.clicked.connect(self.on_J_clicked)
        self.K.clicked.connect(self.on_K_clicked)
        self.L.clicked.connect(self.on_L_clicked)
        self.M.clicked.connect(self.on_M_clicked)
        self.N.clicked.connect(self.on_N_clicked)
        self.O.clicked.connect(self.on_O_clicked)
        self.P.clicked.connect(self.on_P_clicked)
        self.Q.clicked.connect(self.on_Q_clicked)
        self.R.clicked.connect(self.on_R_clicked)
        self.S.clicked.connect(self.on_S_clicked)
        self.T.clicked.connect(self.on_T_clicked)
        self.U.clicked.connect(self.on_U_clicked)
        self.V.clicked.connect(self.on_V_clicked)
        self.W.clicked.connect(self.on_W_clicked)
        self.X.clicked.connect(self.on_X_clicked)
        self.Y.clicked.connect(self.on_Y_clicked)
        self.Z.clicked.connect(self.on_Z_clicked)
        self.actionLeaderboards.triggered.connect(self.leaderboard)
        self.savenexit_button.clicked.connect(self.save_exit)
        self.pushButton_3.clicked.connect(MainWindow.close)
        self.pushButton_4.clicked.connect(self.sign_up_enter)
        self.pushButton_2.clicked.connect(MainWindow.close)
        self.pushButton.clicked.connect(self.sign_in_enter)
        self.actionExit.triggered.connect(MainWindow.close)
        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.hint_button.setText(_translate("MainWindow", "Hint"))
        self.label.setText(_translate("MainWindow", "User :"))
        self.label_2.setText(_translate("MainWindow", "Score :"))
        self.label_3.setText(_translate("MainWindow", "Highscore :"))
        self.A.setText(_translate("MainWindow", "A"))
        self.B.setText(_translate("MainWindow", "B"))
        self.C.setText(_translate("MainWindow", "C"))
        self.D.setText(_translate("MainWindow", "D"))
        self.E.setText(_translate("MainWindow", "E"))
        self.F.setText(_translate("MainWindow", "F"))
        self.G.setText(_translate("MainWindow", "G"))
        self.H.setText(_translate("MainWindow", "H"))
        self.I.setText(_translate("MainWindow", "I"))
        self.J.setText(_translate("MainWindow", "J"))
        self.K.setText(_translate("MainWindow", "K"))
        self.L.setText(_translate("MainWindow", "L"))
        self.M.setText(_translate("MainWindow", "M"))
        self.N.setText(_translate("MainWindow", "N"))
        self.O.setText(_translate("MainWindow", "O"))
        self.P.setText(_translate("MainWindow", "P"))
        self.Q.setText(_translate("MainWindow", "Q"))
        self.R.setText(_translate("MainWindow", "R"))
        self.S.setText(_translate("MainWindow", "S"))
        self.T.setText(_translate("MainWindow", "T"))
        self.U.setText(_translate("MainWindow", "U"))
        self.V.setText(_translate("MainWindow", "V"))
        self.W.setText(_translate("MainWindow", "W"))
        self.X.setText(_translate("MainWindow", "X"))
        self.Y.setText(_translate("MainWindow", "Y"))
        self.Z.setText(_translate("MainWindow", "Z"))
        self.savenexit_button.setText(_translate("MainWindow", "Save and Exit"))
        self.label_4.setText(_translate("MainWindow", "Username:"))
        self.pushButton_2.setText(_translate("MainWindow", "Exit"))
        self.pushButton.setText(_translate("MainWindow", "Enter"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.signin), _translate("MainWindow", "sign in"))
        self.pushButton_3.setText(_translate("MainWindow", "Exit"))
        self.pushButton_4.setText(_translate("MainWindow", "Enter"))
        self.label_5.setText(_translate("MainWindow", "Username:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.signup), _translate("MainWindow", "sign up"))
        self.menufile.setTitle(_translate("MainWindow", "file"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuAbout.setTitle(_translate("MainWindow", "Help"))
        self.actionNew_Game.setText(_translate("MainWindow", "New Game"))
        self.actionSwith_User.setText(_translate("MainWindow", "Swith User"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
        self.actionLeaderboards.setText(_translate("MainWindow", "Leaderboards"))
        self.actionUser_Info.setText(_translate("MainWindow", "User Info"))
        self.actionSource_Info.setText(_translate("MainWindow", "Source Info"))
        self.actionHangman_Help.setText(_translate("MainWindow", "Hangman Help"))
        self.actionAbout_Us.setText(_translate("MainWindow", "About Us"))

    def sign_in_enter(self):
        global Player
        self.warninglabel_2.setText('')
        self.warninglabel.setText("")
        username = self.lineEdit.text()
        if username == "":
            self.warninglabel.setText("invalid username")
            return
        status = check_username(username)
        if status:
            Player = person(status[0],status[1])
            self.build_up_game(username,'0',str(status[1]))
        else:
            self.warninglabel.setText("no username found")
        
    def sign_up_enter(self):
        global Player
        self.warninglabel_2.setText('')
        self.warninglabel.setText("")
        username = self.lineEdit_2.text()
        if username == "":
            self.warninglabel_2.setText("invalid username")
            return
        status = check_username(username)
        if status:
            self.warninglabel_2.setText("username already taken")
        else:
            add_user(username)
            Player = person(username,0)
            self.build_up_game(username,'0','0')
    
    def build_up_game(self,username,score,highscore):
        global Player
        self.highscore_label.setText(highscore)
        self.username_label.setText(username)
        self.score_label.setText(score)
        self.main_window.resize(1100,650)
        self.main_window.setFixedSize(1100,650)
        self.initial_page.hide()
        self.groupBox_2.show()
        Player.current_score = 0
        self.get_game_ready()
        

    def get_game_ready(self):
        global Player
        Player.wrong_inputs = 0
        Player.correct_inputs = 0
        self.A.setEnabled(True)
        self.B.setEnabled(True)
        self.C.setEnabled(True)
        self.D.setEnabled(True)
        self.E.setEnabled(True)
        self.F.setEnabled(True)
        self.G.setEnabled(True)
        self.H.setEnabled(True)
        self.I.setEnabled(True)
        self.J.setEnabled(True)
        self.L.setEnabled(True)
        self.K.setEnabled(True)
        self.M.setEnabled(True)
        self.N.setEnabled(True)
        self.O.setEnabled(True)
        self.P.setEnabled(True)
        self.Q.setEnabled(True)
        self.R.setEnabled(True)
        self.S.setEnabled(True)
        self.T.setEnabled(True)
        self.U.setEnabled(True)
        self.V.setEnabled(True)
        self.W.setEnabled(True)
        self.X.setEnabled(True)
        self.Y.setEnabled(True)
        self.Z.setEnabled(True)      
        self.line1.hide()
        self.line2.hide()
        self.line3.hide()
        self.line4.hide()
        self.line_5.hide()
        self.line_6.hide()
        self.line_7.hide()
        self.line_8.hide()
        self.line_9.hide()
        self.line_10.hide()
        self.line_11.hide()
        self.line_12.hide()
        self.line_13.hide()
        self.line_14.hide()
        self.line_15.hide()
        self.line_16.hide()
        a = random.random()
        b = 0
        if a > 0.5:
            b = random.randint(1, 2241)
            with sq.connect('wordslist.sqlite3') as datab:
                command = "SELECT value FROM lwords WHERE ID = '{}'".format(b)
                cursor = datab.execute(command)
                for x in cursor:
                    Player.word = x[0][:-1]
        else:
            b = random.randint(1,5459)
            with sq.connect('wordslist.sqlite3') as datab:
                command = "SELECT value FROM mwords WHERE ID = '{}'".format(b)
                cursor = datab.execute(command)
                for x in cursor:
                    Player.word = x[0][:-1]
    
        print("word:'{}'".format(Player.word))
        # print("length:",len(Player.word))
        strin = '_ ' *(len(Player.word))
        strin = strin[:-1]
        # print("label length:",len(strin))
        self.word_label.setText(strin)
        Player.last_state = strin
        self.gamer = Player

    def playing(self,key):
        key = key.lower()
        status = key in self.gamer.word
        # print(len(self.gamer.word))
        if status:
            self.gamer.current_score += 100
            for i in range(len(self.gamer.word)):
                if self.gamer.word[i] == key:
                    self.gamer.correct_inputs += 1
                    idx = 2*i
                    # print("idx=",idx)
                    self.gamer.last_state=self.gamer.last_state[:idx]+key+self.gamer.last_state[idx+1:]
        else:
            if self.gamer.current_score > 0:
                self.gamer.current_score -= 10
            self.gamer.wrong_inputs += 1
            wrongs = self.gamer.wrong_inputs
            if wrongs == 1:
                self.line1.show()
            elif wrongs == 2:
                self.line2.show()
            elif wrongs == 3:
                self.line3.show()
            elif wrongs == 4:
                self.line4.show()
            elif wrongs == 5:
                self.line_5.show()
                self.line_6.show()
                self.line_7.show()
                self.line_8.show()
                self.line_15.show()
                self.line_16.show()
                self.line_14.show()
            elif wrongs == 6:
                self.line_9.show()
                self.line_10.show()
                self.line_11.show()
                self.line_12.show()
                self.line_13.show()
        self.word_label.setText(self.gamer.last_state)
        self.score_label.setText(str(self.gamer.current_score))
        if self.gamer.current_score > self.gamer.highscore:
            self.gamer.highscore = self.gamer.current_score
            self.highscore_label.setText(str(self.gamer.highscore))
        if self.gamer.correct_inputs == len(self.gamer.word):
            QtWidgets.QMessageBox.information(self.main_window,"Congrats","you made it!")
            self.get_game_ready()
        elif self.gamer.wrong_inputs == 6:
            QtWidgets.QMessageBox.warning(self.main_window,'shame','you lost this round\nthe word was "{}"'.format(self.gamer.word))
            self.get_game_ready()

    def on_A_clicked(self):
        self.A.setEnabled(False)
        self.playing("A")
    def on_B_clicked(self):
        self.B.setEnabled(False)
        self.playing("B")
    def on_C_clicked(self):
        self.C.setEnabled(False)
        self.playing('C')
    def on_D_clicked(self):
        self.D.setEnabled(False)
        self.playing('D')
    def on_E_clicked(self):
        self.E.setEnabled(False)
        self.playing('E')
    def on_F_clicked(self):
        self.F.setEnabled(False)
        self.playing('F')
    def on_G_clicked(self):
        self.G.setEnabled(False)
        self.playing('G')
    def on_H_clicked(self):
        self.H.setEnabled(False)
        self.playing('H')
    def on_I_clicked(self):
        self.I.setEnabled(False)
        self.playing('I')
    def on_J_clicked(self):
        self.J.setEnabled(False)
        self.playing('J')
    def on_K_clicked(self):
        self.K.setEnabled(False)
        self.playing('K')
    def on_L_clicked(self):
        self.L.setEnabled(False)
        self.playing('L')
    def on_M_clicked(self):
        self.M.setEnabled(False)
        self.playing('M')
    def on_N_clicked(self):
        self.N.setEnabled(False)
        self.playing('N')
    def on_O_clicked(self):
        self.O.setEnabled(False)
        self.playing('O')
    def on_P_clicked(self):
        self.P.setEnabled(False)
        self.playing('P')
    def on_Q_clicked(self):
        self.Q.setEnabled(False)
        self.playing('Q')
    def on_R_clicked(self):
        self.R.setEnabled(False)
        self.playing('R')
    def on_S_clicked(self):
        self.S.setEnabled(False)
        self.playing('S')
    def on_T_clicked(self):
        self.T.setEnabled(False)
        self.playing('T')
    def on_U_clicked(self):
        self.U.setEnabled(False)
        self.playing('U')
    def on_V_clicked(self):
        self.V.setEnabled(False)
        self.playing('V')
    def on_W_clicked(self):
        self.W.setEnabled(False)
        self.playing('W')
    def on_X_clicked(self):
        self.X.setEnabled(False)
        self.playing('X')
    def on_Y_clicked(self):
        self.Y.setEnabled(False)
        self.playing('Y')
    def on_Z_clicked(self):
        self.Z.setEnabled(False)
        self.playing('Z')
    
    def save_exit(self):
        with sq.connect("users.sqlite3") as save:
            command = 'UPDATE users SET highscore = ? WHERE username = ?'
            save.execute(command,tuple((self.gamer.highscore,self.gamer.username)))
            save.commit()
        self.main_window.close()

    def leaderboard(self):
        Dialog = QtWidgets.QDialog()
        ui = leaderboards.Ui_Dialog()
        ui.setupUi(Dialog)
        Dialog.exec_()
        
        
def add_user(username):
    with sq.connect("users.sqlite3") as dvb:
            command = "INSERT INTO users VALUES(?, ?)"
            dvb.execute(command,tuple((username,0)))
            dvb.commit

def check_username(username):
    with sq.connect("users.sqlite3") as dvb:
            command = "SELECT * FROM users WHERE username = '{}'".format(username)
            cursor = dvb.execute(command)
            for x in cursor:
                return x
            

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
