# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gamepage.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1018, 696)
        font = QtGui.QFont()
        font.setPointSize(9)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.word_label = QtWidgets.QLabel(self.centralwidget)
        self.word_label.setGeometry(QtCore.QRect(560, 150, 401, 71))
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.word_label.setFont(font)
        self.word_label.setLineWidth(1)
        self.word_label.setMidLineWidth(1)
        self.word_label.setText("")
        self.word_label.setAlignment(QtCore.Qt.AlignCenter)
        self.word_label.setWordWrap(False)
        self.word_label.setIndent(-1)
        self.word_label.setObjectName("word_label")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setEnabled(True)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 221, 121))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.widget = QtWidgets.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(0, 20, 221, 90))
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.username_label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(9)
        self.username_label.setFont(font)
        self.username_label.setText("")
        self.username_label.setObjectName("username_label")
        self.verticalLayout_3.addWidget(self.username_label)
        self.score_label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(9)
        self.score_label.setFont(font)
        self.score_label.setText("")
        self.score_label.setObjectName("score_label")
        self.verticalLayout_3.addWidget(self.score_label)
        self.highscore_label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(9)
        self.highscore_label.setFont(font)
        self.highscore_label.setText("")
        self.highscore_label.setObjectName("highscore_label")
        self.verticalLayout_3.addWidget(self.highscore_label)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.line1 = QtWidgets.QFrame(self.centralwidget)
        self.line1.setGeometry(QtCore.QRect(40, 550, 150, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line1.sizePolicy().hasHeightForWidth())
        self.line1.setSizePolicy(sizePolicy)
        self.line1.setMinimumSize(QtCore.QSize(150, 30))
        self.line1.setMaximumSize(QtCore.QSize(150, 30))
        self.line1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line1.setLineWidth(5)
        self.line1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line1.setObjectName("line1")
        self.line2 = QtWidgets.QFrame(self.centralwidget)
        self.line2.setGeometry(QtCore.QRect(100, 215, 30, 350))
        self.line2.setMinimumSize(QtCore.QSize(30, 350))
        self.line2.setMaximumSize(QtCore.QSize(30, 350))
        self.line2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line2.setLineWidth(5)
        self.line2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line2.setObjectName("line2")
        self.line3 = QtWidgets.QFrame(self.centralwidget)
        self.line3.setGeometry(QtCore.QRect(114, 202, 251, 31))
        self.line3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line3.setLineWidth(5)
        self.line3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line3.setObjectName("line3")
        self.line4 = QtWidgets.QFrame(self.centralwidget)
        self.line4.setGeometry(QtCore.QRect(355, 216, 16, 51))
        self.line4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line4.setLineWidth(5)
        self.line4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line4.setObjectName("line4")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(330, 268, 16, 51))
        self.line_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_5.setLineWidth(2)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(380, 268, 16, 51))
        self.line_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_6.setLineWidth(2)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(338, 310, 51, 16))
        self.line_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_7.setLineWidth(2)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(338, 260, 51, 16))
        self.line_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_8.setLineWidth(2)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(self.centralwidget)
        self.line_9.setGeometry(QtCore.QRect(360, 320, 16, 91))
        self.line_9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_9.setLineWidth(2)
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setObjectName("line_9")
        self.line_10 = QtWidgets.QFrame(self.centralwidget)
        self.line_10.setGeometry(QtCore.QRect(370, 402, 51, 16))
        self.line_10.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_10.setLineWidth(2)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setObjectName("line_10")
        self.line_11 = QtWidgets.QFrame(self.centralwidget)
        self.line_11.setGeometry(QtCore.QRect(320, 402, 51, 16))
        self.line_11.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_11.setLineWidth(2)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setObjectName("line_11")
        self.line_12 = QtWidgets.QFrame(self.centralwidget)
        self.line_12.setGeometry(QtCore.QRect(325, 350, 42, 16))
        self.line_12.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_12.setLineWidth(2)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setObjectName("line_12")
        self.line_13 = QtWidgets.QFrame(self.centralwidget)
        self.line_13.setGeometry(QtCore.QRect(368, 350, 42, 16))
        self.line_13.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_13.setLineWidth(2)
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setObjectName("line_13")
        self.line_14 = QtWidgets.QFrame(self.centralwidget)
        self.line_14.setGeometry(QtCore.QRect(340, 280, 16, 16))
        self.line_14.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_14.setLineWidth(2)
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setObjectName("line_14")
        self.line_15 = QtWidgets.QFrame(self.centralwidget)
        self.line_15.setGeometry(QtCore.QRect(370, 280, 16, 16))
        self.line_15.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_15.setLineWidth(2)
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setObjectName("line_15")
        self.line_16 = QtWidgets.QFrame(self.centralwidget)
        self.line_16.setGeometry(QtCore.QRect(352, 300, 21, 16))
        self.line_16.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_16.setLineWidth(2)
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setObjectName("line_16")
        self.hint_button = QtWidgets.QPushButton(self.centralwidget)
        self.hint_button.setGeometry(QtCore.QRect(410, 50, 91, 31))
        self.hint_button.setObjectName("hint_button")
        self.savenexit_button = QtWidgets.QPushButton(self.centralwidget)
        self.savenexit_button.setGeometry(QtCore.QRect(720, 590, 121, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.savenexit_button.setFont(font)
        self.savenexit_button.setObjectName("savenexit_button")
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(550, 330, 427, 145))
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, -1, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.A = QtWidgets.QPushButton(self.widget1)
        self.A.setMinimumSize(QtCore.QSize(35, 35))
        self.A.setMaximumSize(QtCore.QSize(35, 35))
        self.A.setObjectName("A")
        self.horizontalLayout.addWidget(self.A)
        self.B = QtWidgets.QPushButton(self.widget1)
        self.B.setMinimumSize(QtCore.QSize(35, 35))
        self.B.setMaximumSize(QtCore.QSize(35, 35))
        self.B.setObjectName("B")
        self.horizontalLayout.addWidget(self.B)
        self.C = QtWidgets.QPushButton(self.widget1)
        self.C.setMinimumSize(QtCore.QSize(35, 35))
        self.C.setMaximumSize(QtCore.QSize(35, 35))
        self.C.setObjectName("C")
        self.horizontalLayout.addWidget(self.C)
        self.D = QtWidgets.QPushButton(self.widget1)
        self.D.setMinimumSize(QtCore.QSize(35, 35))
        self.D.setMaximumSize(QtCore.QSize(35, 35))
        self.D.setObjectName("D")
        self.horizontalLayout.addWidget(self.D)
        self.E = QtWidgets.QPushButton(self.widget1)
        self.E.setMinimumSize(QtCore.QSize(35, 35))
        self.E.setMaximumSize(QtCore.QSize(35, 35))
        self.E.setObjectName("E")
        self.horizontalLayout.addWidget(self.E)
        self.F = QtWidgets.QPushButton(self.widget1)
        self.F.setMinimumSize(QtCore.QSize(35, 35))
        self.F.setMaximumSize(QtCore.QSize(35, 35))
        self.F.setObjectName("F")
        self.horizontalLayout.addWidget(self.F)
        self.G = QtWidgets.QPushButton(self.widget1)
        self.G.setMinimumSize(QtCore.QSize(35, 35))
        self.G.setMaximumSize(QtCore.QSize(35, 35))
        self.G.setObjectName("G")
        self.horizontalLayout.addWidget(self.G)
        self.H = QtWidgets.QPushButton(self.widget1)
        self.H.setMinimumSize(QtCore.QSize(35, 35))
        self.H.setMaximumSize(QtCore.QSize(35, 35))
        self.H.setObjectName("H")
        self.horizontalLayout.addWidget(self.H)
        self.I = QtWidgets.QPushButton(self.widget1)
        self.I.setEnabled(True)
        self.I.setMinimumSize(QtCore.QSize(35, 35))
        self.I.setMaximumSize(QtCore.QSize(35, 35))
        self.I.setObjectName("I")
        self.horizontalLayout.addWidget(self.I)
        self.J = QtWidgets.QPushButton(self.widget1)
        self.J.setMinimumSize(QtCore.QSize(35, 35))
        self.J.setMaximumSize(QtCore.QSize(35, 35))
        self.J.setObjectName("J")
        self.horizontalLayout.addWidget(self.J)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, -1, 10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.K = QtWidgets.QPushButton(self.widget1)
        self.K.setMinimumSize(QtCore.QSize(35, 35))
        self.K.setMaximumSize(QtCore.QSize(35, 35))
        self.K.setObjectName("K")
        self.horizontalLayout_2.addWidget(self.K)
        self.L = QtWidgets.QPushButton(self.widget1)
        self.L.setMinimumSize(QtCore.QSize(35, 35))
        self.L.setMaximumSize(QtCore.QSize(35, 35))
        self.L.setObjectName("L")
        self.horizontalLayout_2.addWidget(self.L)
        self.M = QtWidgets.QPushButton(self.widget1)
        self.M.setMinimumSize(QtCore.QSize(35, 35))
        self.M.setMaximumSize(QtCore.QSize(35, 35))
        self.M.setObjectName("M")
        self.horizontalLayout_2.addWidget(self.M)
        self.N = QtWidgets.QPushButton(self.widget1)
        self.N.setMinimumSize(QtCore.QSize(35, 35))
        self.N.setMaximumSize(QtCore.QSize(35, 35))
        self.N.setObjectName("N")
        self.horizontalLayout_2.addWidget(self.N)
        self.O = QtWidgets.QPushButton(self.widget1)
        self.O.setMinimumSize(QtCore.QSize(35, 35))
        self.O.setMaximumSize(QtCore.QSize(35, 35))
        self.O.setObjectName("O")
        self.horizontalLayout_2.addWidget(self.O)
        self.P = QtWidgets.QPushButton(self.widget1)
        self.P.setMinimumSize(QtCore.QSize(35, 35))
        self.P.setMaximumSize(QtCore.QSize(35, 35))
        self.P.setObjectName("P")
        self.horizontalLayout_2.addWidget(self.P)
        self.Q = QtWidgets.QPushButton(self.widget1)
        self.Q.setMinimumSize(QtCore.QSize(35, 35))
        self.Q.setMaximumSize(QtCore.QSize(35, 35))
        self.Q.setObjectName("Q")
        self.horizontalLayout_2.addWidget(self.Q)
        self.R = QtWidgets.QPushButton(self.widget1)
        self.R.setMinimumSize(QtCore.QSize(35, 35))
        self.R.setMaximumSize(QtCore.QSize(35, 35))
        self.R.setObjectName("R")
        self.horizontalLayout_2.addWidget(self.R)
        self.S = QtWidgets.QPushButton(self.widget1)
        self.S.setMinimumSize(QtCore.QSize(35, 35))
        self.S.setMaximumSize(QtCore.QSize(35, 35))
        self.S.setObjectName("S")
        self.horizontalLayout_2.addWidget(self.S)
        self.T = QtWidgets.QPushButton(self.widget1)
        self.T.setMinimumSize(QtCore.QSize(35, 35))
        self.T.setMaximumSize(QtCore.QSize(35, 35))
        self.T.setObjectName("T")
        self.horizontalLayout_2.addWidget(self.T)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(85, -1, 85, -1)
        self.horizontalLayout_3.setSpacing(7)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.U = QtWidgets.QPushButton(self.widget1)
        self.U.setMinimumSize(QtCore.QSize(35, 35))
        self.U.setMaximumSize(QtCore.QSize(35, 35))
        self.U.setObjectName("U")
        self.horizontalLayout_3.addWidget(self.U)
        self.V = QtWidgets.QPushButton(self.widget1)
        self.V.setMinimumSize(QtCore.QSize(35, 35))
        self.V.setMaximumSize(QtCore.QSize(35, 35))
        self.V.setObjectName("V")
        self.horizontalLayout_3.addWidget(self.V)
        self.W = QtWidgets.QPushButton(self.widget1)
        self.W.setMinimumSize(QtCore.QSize(35, 35))
        self.W.setMaximumSize(QtCore.QSize(35, 35))
        self.W.setObjectName("W")
        self.horizontalLayout_3.addWidget(self.W)
        self.X = QtWidgets.QPushButton(self.widget1)
        self.X.setMinimumSize(QtCore.QSize(35, 35))
        self.X.setMaximumSize(QtCore.QSize(35, 35))
        self.X.setObjectName("X")
        self.horizontalLayout_3.addWidget(self.X)
        self.Y = QtWidgets.QPushButton(self.widget1)
        self.Y.setMinimumSize(QtCore.QSize(35, 35))
        self.Y.setMaximumSize(QtCore.QSize(35, 35))
        self.Y.setObjectName("Y")
        self.horizontalLayout_3.addWidget(self.Y)
        self.Z = QtWidgets.QPushButton(self.widget1)
        self.Z.setMinimumSize(QtCore.QSize(35, 35))
        self.Z.setMaximumSize(QtCore.QSize(35, 35))
        self.Z.setObjectName("Z")
        self.horizontalLayout_3.addWidget(self.Z)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1018, 26))
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setGeometry(QtCore.QRect(288, 187, 159, 150))
        self.menufile.setObjectName("menufile")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew_Game = QtWidgets.QAction(MainWindow)
        self.actionNew_Game.setObjectName("actionNew_Game")
        self.actionSwith_User = QtWidgets.QAction(MainWindow)
        self.actionSwith_User.setObjectName("actionSwith_User")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionLeaderboards = QtWidgets.QAction(MainWindow)
        self.actionLeaderboards.setObjectName("actionLeaderboards")
        self.actionUser_Info = QtWidgets.QAction(MainWindow)
        self.actionUser_Info.setObjectName("actionUser_Info")
        self.actionSource_Info = QtWidgets.QAction(MainWindow)
        self.actionSource_Info.setObjectName("actionSource_Info")
        self.actionHangman_Help = QtWidgets.QAction(MainWindow)
        self.actionHangman_Help.setObjectName("actionHangman_Help")
        self.actionAbout_Us = QtWidgets.QAction(MainWindow)
        self.actionAbout_Us.setObjectName("actionAbout_Us")
        self.menufile.addAction(self.actionNew_Game)
        self.menufile.addAction(self.actionSwith_User)
        self.menufile.addAction(self.actionSettings)
        self.menufile.addAction(self.actionExit)
        self.menuView.addAction(self.actionLeaderboards)
        self.menuView.addAction(self.actionUser_Info)
        self.menuView.addAction(self.actionSource_Info)
        self.menuAbout.addAction(self.actionHangman_Help)
        self.menuAbout.addAction(self.actionAbout_Us)
        self.menubar.addAction(self.menufile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "User :"))
        self.label_2.setText(_translate("MainWindow", "Score :"))
        self.label_3.setText(_translate("MainWindow", "Highscore :"))
        self.hint_button.setText(_translate("MainWindow", "Hint"))
        self.savenexit_button.setText(_translate("MainWindow", "Save and Exit"))
        self.A.setText(_translate("MainWindow", "A"))
        self.B.setText(_translate("MainWindow", "B"))
        self.C.setText(_translate("MainWindow", "C"))
        self.D.setText(_translate("MainWindow", "D"))
        self.E.setText(_translate("MainWindow", "E"))
        self.F.setText(_translate("MainWindow", "F"))
        self.G.setText(_translate("MainWindow", "G"))
        self.H.setText(_translate("MainWindow", "H"))
        self.I.setText(_translate("MainWindow", "I"))
        self.J.setText(_translate("MainWindow", "J"))
        self.K.setText(_translate("MainWindow", "K"))
        self.L.setText(_translate("MainWindow", "L"))
        self.M.setText(_translate("MainWindow", "M"))
        self.N.setText(_translate("MainWindow", "N"))
        self.O.setText(_translate("MainWindow", "O"))
        self.P.setText(_translate("MainWindow", "P"))
        self.Q.setText(_translate("MainWindow", "Q"))
        self.R.setText(_translate("MainWindow", "R"))
        self.S.setText(_translate("MainWindow", "S"))
        self.T.setText(_translate("MainWindow", "T"))
        self.U.setText(_translate("MainWindow", "U"))
        self.V.setText(_translate("MainWindow", "V"))
        self.W.setText(_translate("MainWindow", "W"))
        self.X.setText(_translate("MainWindow", "X"))
        self.Y.setText(_translate("MainWindow", "Y"))
        self.Z.setText(_translate("MainWindow", "Z"))
        self.menufile.setTitle(_translate("MainWindow", "file"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuAbout.setTitle(_translate("MainWindow", "Help"))
        self.actionNew_Game.setText(_translate("MainWindow", "New Game"))
        self.actionSwith_User.setText(_translate("MainWindow", "Swith User"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
        self.actionLeaderboards.setText(_translate("MainWindow", "Leaderboards"))
        self.actionUser_Info.setText(_translate("MainWindow", "User Info"))
        self.actionSource_Info.setText(_translate("MainWindow", "Source Info"))
        self.actionHangman_Help.setText(_translate("MainWindow", "Hangman Help"))
        self.actionAbout_Us.setText(_translate("MainWindow", "About Us"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
